package PluginReference;

package PluginReference;

/** 
 * GameRule Type
 */ 			
public enum MC_GameRuleType
{
	UNSPECIFIED,
	DO_FIRE_TICK,
	MOB_GRIEFING,
	KEEP_INVENTORY,
	DO_MOB_SPAWNING,
	DO_MOB_LOOT,
	DO_TILE_DROPS,
	COMMAND_BLOCK_OUTPUT,
	NATURAL_REGENERATION,
	DO_DAYLIGHT_CYCLE,
	LOG_ADMIN_COMMANDS,
	SHOW_DEATH_MESSAGES,
	SEND_COMMAND_FEEDBACK,
	REDUCED_DEBUG_INFO,
	DO_ENTITY_DROPS,
	SPECTATORS_GENERATE_CHUNKS,
	DISABLE_ELYTRA_MOVEMENT_CHECK,
	DO_WEATHER_CYCLE,
	DO_LIMITED_CRAFTING,
    ANNOUNCE_ADVANCEMENTS
}