package PluginReference;

public enum MC_MiscGriefType
{
	ENDERDRAGON_BRUSH,
	ENDERMAN_PICKUP_BLOCK,
	ENDERMAN_PLACE_CARRIED_BLOCK,
	SHEEP_GRAZING_GRASS,
	SILVERFISH_BREAK_MONSTER_EGG_BLOCK,
	RABBIT_EATS_CARROT,
	VILLAGER_HARVEST,
	VILLAGER_PLANT_SEEDS,
	WITHER_BREAK,
	ZOMBIE_DOOR_BREAK
}
