package PluginReference;

import java.util.concurrent.ConcurrentHashMap;

/** 
 * Block-related utility functions and maps available to Rainbow plugins.
 */ 			
public class BlockHelper
{
	 /** 
     * Map of Block ID to internal Block Name
     * For example, 8 maps to 'flowing_water'
     */ 			
	public static ConcurrentHashMap<Integer, String> mapBlockNames = new ConcurrentHashMap<Integer, String>();
	 /** 
     * Map of ID:Subtype string to friendly Block Name
     * For example, "126:5" maps to "Dark Oak Wood Slab"
     */ 			
	public static ConcurrentHashMap<String, String> mapItemNames = new ConcurrentHashMap<String, String>();
	 /** 
     * Map of ID to number of subtypes
     * For example, ID 1 maps to 7 because there are 7 stone subtypes in MC 1.8
     */ 			
	public static ConcurrentHashMap<Integer, Integer> mapNumSubtypes = new ConcurrentHashMap<Integer, Integer>();

	 /** 
     * Get internal block name from ID.
     * For example, returns "flowing_water" for ID 8.
     * @return Block Name
     */ 			
	public static String getBlockName(int blockID)
	{
		String res = mapBlockNames.get(blockID);
		if (res != null) return res;
		res = ("BlockID_" + blockID);
		//System.out.println("----- DBG: " + res + " -----");
		return res;
	}

	 /** 
     * Translates (ID=139,Subtype=1) into "Mossy Cobblestone Wall" and so forth.

     * @return Friendly Name
     */ 			
	public static String getBlockFriendlyName(int blockID, int subType)
	{
		Integer numSubTypes = mapNumSubtypes.get(blockID);
		if(numSubTypes == null) numSubTypes = 1;
		if(numSubTypes <= 1)
		{
			String key = blockID + ":0";
			String res = mapItemNames.get(key);
			return (res != null) ? res : ("BlockID_" + blockID + ":" + subType);
		}

		// Reduce by next highest power of 2...
		// This is because the dmg value may include other bitwise markers like directional attribute
		int powTwo = 2;
		for(int i=0; i<5; i++)
		{
			if(numSubTypes <= powTwo)
			{
				subType %= powTwo;
				break;
			}
			powTwo *= 2;
		}
		// Lookup based on refined dmg value...

		String key = blockID + ":" + subType;
		String res = mapItemNames.get(key);
		if (res != null) return res;
		
		res = ("BlockID_" + blockID + ":" + subType);
		//System.out.println("----- DBG: " + res + " -----");
		return res;
	}
	
	 /** 
     * Translates Minecraft integer representation of a block into just the Block ID.
     * See PluginBase.onBlockBroke() for an example of where this is used. 
     * @return Block ID
     */ 			
	public static int getBlockID_FromKey(int blockKey)
	{
		int blockID = blockKey & ((1 << 12) - 1);
		return blockID;
	}

	 /** 
     * Translates Minecraft integer representation of a block into just the Block Subtype
     * See PluginBase.onBlockBroke() for an example of where this is used. 
     * @return Block Subtype
     */ 			
	public static int getBlockSubtype_FromKey(int blockKey)
	{
		return (blockKey >> 12);
	}

	static
	{
		mapBlockNames.put(0, "air");
		mapBlockNames.put(1, "stone");
		mapBlockNames.put(2, "grass");
		mapBlockNames.put(3, "dirt");
		mapBlockNames.put(4, "cobblestone");
		mapBlockNames.put(5, "planks");
		mapBlockNames.put(6, "sapling");
		mapBlockNames.put(7, "bedrock");
		mapBlockNames.put(8, "flowing_water");
		mapBlockNames.put(9, "water");
		mapBlockNames.put(10, "flowing_lava");
		mapBlockNames.put(11, "lava");
		mapBlockNames.put(12, "sand");
		mapBlockNames.put(13, "gravel");
		mapBlockNames.put(14, "gold_ore");
		mapBlockNames.put(15, "iron_ore");
		mapBlockNames.put(16, "coal_ore");
		mapBlockNames.put(17, "log");
		mapBlockNames.put(18, "leaves");
		mapBlockNames.put(19, "sponge");
		mapBlockNames.put(20, "glass");
		mapBlockNames.put(21, "lapis_ore");
		mapBlockNames.put(22, "lapis_block");
		mapBlockNames.put(23, "dispenser");
		mapBlockNames.put(24, "sandstone");
		mapBlockNames.put(25, "noteblock");
		mapBlockNames.put(26, "bed");
		mapBlockNames.put(27, "golden_rail");
		mapBlockNames.put(28, "detector_rail");
		mapBlockNames.put(29, "sticky_piston");
		mapBlockNames.put(30, "web");
		mapBlockNames.put(31, "tallgrass");
		mapBlockNames.put(32, "deadbush");
		mapBlockNames.put(33, "piston");
		mapBlockNames.put(34, "piston_head");
		mapBlockNames.put(35, "wool");
		mapBlockNames.put(36, "piston_extension");
		mapBlockNames.put(37, "yellow_flower");
		mapBlockNames.put(38, "red_flower");
		mapBlockNames.put(39, "brown_mushroom");
		mapBlockNames.put(40, "red_mushroom");
		mapBlockNames.put(41, "gold_block");
		mapBlockNames.put(42, "iron_block");
		mapBlockNames.put(43, "double_stone_slab");
		mapBlockNames.put(44, "stone_slab");
		mapBlockNames.put(45, "brick_block");
		mapBlockNames.put(46, "tnt");
		mapBlockNames.put(47, "bookshelf");
		mapBlockNames.put(48, "mossy_cobblestone");
		mapBlockNames.put(49, "obsidian");
		mapBlockNames.put(50, "torch");
		mapBlockNames.put(51, "fire");
		mapBlockNames.put(52, "mob_spawner");
		mapBlockNames.put(53, "oak_stairs");
		mapBlockNames.put(54, "chest");
		mapBlockNames.put(55, "redstone_wire");
		mapBlockNames.put(56, "diamond_ore");
		mapBlockNames.put(57, "diamond_block");
		mapBlockNames.put(58, "crafting_table");
		mapBlockNames.put(59, "wheat");
		mapBlockNames.put(60, "farmland");
		mapBlockNames.put(61, "furnace");
		mapBlockNames.put(62, "lit_furnace");
		mapBlockNames.put(63, "standing_sign");
		mapBlockNames.put(64, "wooden_door");
		mapBlockNames.put(65, "ladder");
		mapBlockNames.put(66, "rail");
		mapBlockNames.put(67, "stone_stairs");
		mapBlockNames.put(68, "wall_sign");
		mapBlockNames.put(69, "lever");
		mapBlockNames.put(70, "stone_pressure_plate");
		mapBlockNames.put(71, "iron_door");
		mapBlockNames.put(72, "wooden_pressure_plate");
		mapBlockNames.put(73, "redstone_ore");
		mapBlockNames.put(74, "lit_redstone_ore");
		mapBlockNames.put(75, "unlit_redstone_torch");
		mapBlockNames.put(76, "redstone_torch");
		mapBlockNames.put(77, "stone_button");
		mapBlockNames.put(78, "snow_layer");
		mapBlockNames.put(79, "ice");
		mapBlockNames.put(80, "snow");
		mapBlockNames.put(81, "cactus");
		mapBlockNames.put(82, "clay");
		mapBlockNames.put(83, "reeds");
		mapBlockNames.put(84, "jukebox");
		mapBlockNames.put(85, "fence");
		mapBlockNames.put(86, "pumpkin");
		mapBlockNames.put(87, "netherrack");
		mapBlockNames.put(88, "soul_sand");
		mapBlockNames.put(89, "glowstone");
		mapBlockNames.put(90, "portal");
		mapBlockNames.put(91, "lit_pumpkin");
		mapBlockNames.put(92, "cake");
		mapBlockNames.put(93, "unpowered_repeater");
		mapBlockNames.put(94, "powered_repeater");
		mapBlockNames.put(95, "stained_glass");
		mapBlockNames.put(96, "trapdoor");
		mapBlockNames.put(97, "monster_egg");
		mapBlockNames.put(98, "stonebrick");
		mapBlockNames.put(99, "brown_mushroom_block");
		mapBlockNames.put(100, "red_mushroom_block");
		mapBlockNames.put(101, "iron_bars");
		mapBlockNames.put(102, "glass_pane");
		mapBlockNames.put(103, "melon_block");
		mapBlockNames.put(104, "pumpkin_stem");
		mapBlockNames.put(105, "melon_stem");
		mapBlockNames.put(106, "vine");
		mapBlockNames.put(107, "fence_gate");
		mapBlockNames.put(108, "brick_stairs");
		mapBlockNames.put(109, "stone_brick_stairs");
		mapBlockNames.put(110, "mycelium");
		mapBlockNames.put(111, "waterlily");
		mapBlockNames.put(112, "nether_brick");
		mapBlockNames.put(113, "nether_brick_fence");
		mapBlockNames.put(114, "nether_brick_stairs");
		mapBlockNames.put(115, "nether_wart");
		mapBlockNames.put(116, "enchanting_table");
		mapBlockNames.put(117, "brewing_stand");
		mapBlockNames.put(118, "cauldron");
		mapBlockNames.put(119, "end_portal");
		mapBlockNames.put(120, "end_portal_frame");
		mapBlockNames.put(121, "end_stone");
		mapBlockNames.put(122, "dragon_egg");
		mapBlockNames.put(123, "redstone_lamp");
		mapBlockNames.put(124, "lit_redstone_lamp");
		mapBlockNames.put(125, "double_wooden_slab");
		mapBlockNames.put(126, "wooden_slab");
		mapBlockNames.put(127, "cocoa");
		mapBlockNames.put(128, "sandstone_stairs");
		mapBlockNames.put(129, "emerald_ore");
		mapBlockNames.put(130, "ender_chest");
		mapBlockNames.put(131, "tripwire_hook");
		mapBlockNames.put(132, "tripwire");
		mapBlockNames.put(133, "emerald_block");
		mapBlockNames.put(134, "spruce_stairs");
		mapBlockNames.put(135, "birch_stairs");
		mapBlockNames.put(136, "jungle_stairs");
		mapBlockNames.put(137, "command_block");
		mapBlockNames.put(138, "beacon");
		mapBlockNames.put(139, "cobblestone_wall");
		mapBlockNames.put(140, "flower_pot");
		mapBlockNames.put(141, "carrots");
		mapBlockNames.put(142, "potatoes");
		mapBlockNames.put(143, "wooden_button");
		mapBlockNames.put(144, "skull");
		mapBlockNames.put(145, "anvil");
		mapBlockNames.put(146, "trapped_chest");
		mapBlockNames.put(147, "light_weighted_pressure_plate");
		mapBlockNames.put(148, "heavy_weighted_pressure_plate");
		mapBlockNames.put(149, "unpowered_comparator");
		mapBlockNames.put(150, "powered_comparator");
		mapBlockNames.put(151, "daylight_detector");
		mapBlockNames.put(152, "redstone_block");
		mapBlockNames.put(153, "quartz_ore");
		mapBlockNames.put(154, "hopper");
		mapBlockNames.put(155, "quartz_block");
		mapBlockNames.put(156, "quartz_stairs");
		mapBlockNames.put(157, "activator_rail");
		mapBlockNames.put(158, "dropper");
		mapBlockNames.put(159, "stained_hardened_clay");
		mapBlockNames.put(160, "stained_glass_pane");
		mapBlockNames.put(161, "leaves2");
		mapBlockNames.put(162, "log2");
		mapBlockNames.put(163, "acacia_stairs");
		mapBlockNames.put(164, "dark_oak_stairs");
		mapBlockNames.put(165, "slime");
		mapBlockNames.put(166, "barrier");
		mapBlockNames.put(167, "iron_trapdoor");
		mapBlockNames.put(168, "prismarine");
		mapBlockNames.put(169, "sea_lantern");
		mapBlockNames.put(170, "hay_block");
		mapBlockNames.put(171, "carpet");
		mapBlockNames.put(172, "hardened_clay");
		mapBlockNames.put(173, "coal_block");
		mapBlockNames.put(174, "packed_ice");
		mapBlockNames.put(175, "double_plant");
		mapBlockNames.put(176, "standing_banner");
		mapBlockNames.put(177, "wall_banner");
		mapBlockNames.put(178, "daylight_detector_inverted");
		mapBlockNames.put(179, "red_sandstone");
		mapBlockNames.put(180, "red_sandstone_stairs");
		mapBlockNames.put(181, "double_stone_slab2");
		mapBlockNames.put(182, "stone_slab2");
		mapBlockNames.put(183, "spruce_fence_gate");
		mapBlockNames.put(184, "birch_fence_gate");
		mapBlockNames.put(185, "jungle_fence_gate");
		mapBlockNames.put(186, "dark_oak_fence_gate");
		mapBlockNames.put(187, "acacia_fence_gate");
		mapBlockNames.put(188, "spruce_fence");
		mapBlockNames.put(189, "birch_fence");
		mapBlockNames.put(190, "jungle_fence");
		mapBlockNames.put(191, "dark_oak_fence");
		mapBlockNames.put(192, "acacia_fence");
		mapBlockNames.put(193, "spruce_door");
		mapBlockNames.put(194, "birch_door");
		mapBlockNames.put(195, "jungle_door");
		mapBlockNames.put(196, "acacia_door");
		mapBlockNames.put(197, "dark_oak_door");
		
		mapItemNames.put("101:0", "Iron Bars");
		mapItemNames.put("102:0", "Glass Pane");
		mapItemNames.put("103:0", "Melon");
		mapItemNames.put("106:0", "Vines");
		mapItemNames.put("107:0", "Oak Fence Gate");
		mapItemNames.put("108:0", "Brick Stairs");
		mapItemNames.put("109:0", "Stone Brick Stairs");
		mapItemNames.put("110:0", "Mycelium");
		mapItemNames.put("111:0", "Lily Pad");
		mapItemNames.put("112:0", "Nether Brick");
		mapItemNames.put("113:0", "Nether Brick Fence");
		mapItemNames.put("114:0", "Nether Brick Stairs");
		mapItemNames.put("116:0", "Enchantment Table");
		mapItemNames.put("120:0", "End Portal");
		mapItemNames.put("121:0", "End Stone");
		mapItemNames.put("122:0", "Dragon Egg");
		mapItemNames.put("123:0", "Redstone Lamp");
		mapItemNames.put("126:0", "Oak Wood Slab");
		mapItemNames.put("126:1", "Spruce Wood Slab");
		mapItemNames.put("126:2", "Birch Wood Slab");
		mapItemNames.put("126:3", "Jungle Wood Slab");
		mapItemNames.put("126:4", "Acacia Wood Slab");
		mapItemNames.put("126:5", "Dark Oak Wood Slab");
		mapItemNames.put("128:0", "Sandstone Stairs");
		mapItemNames.put("129:0", "Emerald Ore");
		mapItemNames.put("12:0", "Sand");
		mapItemNames.put("12:1", "Red Sand");
		mapItemNames.put("130:0", "Ender Chest");
		mapItemNames.put("131:0", "Tripwire Hook");
		mapItemNames.put("133:0", "Block of Emerald");
		mapItemNames.put("134:0", "Spruce Wood Stairs");
		mapItemNames.put("135:0", "Birch Wood Stairs");
		mapItemNames.put("136:0", "Jungle Wood Stairs");
		mapItemNames.put("137:0", "Command Block");
		mapItemNames.put("138:0", "Beacon");
		mapItemNames.put("139:0", "Cobblestone Wall");
		mapItemNames.put("139:1", "Mossy Cobblestone Wall");
		mapItemNames.put("13:0", "Gravel");
		mapItemNames.put("145:0", "Anvil");
		mapItemNames.put("145:1", "Slightly Damaged Anvil");
		mapItemNames.put("145:2", "Very Damaged Anvil");
		mapItemNames.put("146:0", "Trapped Chest");
		mapItemNames.put("147:0", "Weighted Pressure Plate (Light)");
		mapItemNames.put("148:0", "Weighted Pressure Plate (Heavy)");
		mapItemNames.put("14:0", "Gold Ore");
		mapItemNames.put("151:0", "Daylight Sensor");
		mapItemNames.put("152:0", "Block of Redstone");
		mapItemNames.put("153:0", "Nether Quartz Ore");
		mapItemNames.put("154:0", "Hopper");
		mapItemNames.put("155:0", "Block of Quartz");
		mapItemNames.put("155:1", "Chiseled Quartz Block");
		mapItemNames.put("155:2", "Pillar Quartz Block");
		mapItemNames.put("156:0", "Quartz Stairs");
		mapItemNames.put("157:0", "Activator Rail");
		mapItemNames.put("158:0", "Dropper");
		mapItemNames.put("159:0", "White Stained Clay");
		mapItemNames.put("159:1", "Orange Stained Clay");
		mapItemNames.put("159:10", "Purple Stained Clay");
		mapItemNames.put("159:11", "Blue Stained Clay");
		mapItemNames.put("159:12", "Brown Stained Clay");
		mapItemNames.put("159:13", "Green Stained Clay");
		mapItemNames.put("159:14", "Red Stained Clay");
		mapItemNames.put("159:15", "Black Stained Clay");
		mapItemNames.put("159:2", "Magenta Stained Clay");
		mapItemNames.put("159:3", "Light Blue Stained Clay");
		mapItemNames.put("159:4", "Yellow Stained Clay");
		mapItemNames.put("159:5", "Lime Stained Clay");
		mapItemNames.put("159:6", "Pink Stained Clay");
		mapItemNames.put("159:7", "Gray Stained Clay");
		mapItemNames.put("159:8", "Light Gray Stained Clay");
		mapItemNames.put("159:9", "Cyan Stained Clay");
		mapItemNames.put("15:0", "Iron Ore");
		mapItemNames.put("160:0", "White Stained Glass Pane");
		mapItemNames.put("160:1", "Orange Stained Glass Pane");
		mapItemNames.put("160:10", "Purple Stained Glass Pane");
		mapItemNames.put("160:11", "Blue Stained Glass Pane");
		mapItemNames.put("160:12", "Brown Stained Glass Pane");
		mapItemNames.put("160:13", "Green Stained Glass Pane");
		mapItemNames.put("160:14", "Red Stained Glass Pane");
		mapItemNames.put("160:15", "Black Stained Glass Pane");
		mapItemNames.put("160:2", "Magenta Stained Glass Pane");
		mapItemNames.put("160:3", "Light Blue Stained Glass Pane");
		mapItemNames.put("160:4", "Yellow Stained Glass Pane");
		mapItemNames.put("160:5", "Lime Stained Glass Pane");
		mapItemNames.put("160:6", "Pink Stained Glass Pane");
		mapItemNames.put("160:7", "Gray Stained Glass Pane");
		mapItemNames.put("160:8", "Light Gray Stained Glass Pane");
		mapItemNames.put("160:9", "Cyan Stained Glass Pane");
		mapItemNames.put("161:0", "Acacia Leaves");
		mapItemNames.put("161:1", "Dark Oak Leaves");
		mapItemNames.put("163:0", "Acacia Wood Stairs");
		mapItemNames.put("164:0", "Dark Oak Wood Stairs");
		mapItemNames.put("165:0", "Slime Block");
		mapItemNames.put("166:0", "Barrier");
		mapItemNames.put("167:0", "Iron Trapdoor");
		mapItemNames.put("168:0", "Prismarine");
		mapItemNames.put("168:1", "Prismarine Bricks");
		mapItemNames.put("168:2", "Dark Prismarine");
		mapItemNames.put("169:0", "Sea Lantern");
		mapItemNames.put("16:0", "Coal Ore");
		mapItemNames.put("170:0", "Hay Bale");
		mapItemNames.put("171:0", "Carpet");
		mapItemNames.put("171:1", "Orange Carpet");
		mapItemNames.put("171:10", "Purple Carpet");
		mapItemNames.put("171:11", "Blue Carpet");
		mapItemNames.put("171:12", "Brown Carpet");
		mapItemNames.put("171:13", "Green Carpet");
		mapItemNames.put("171:14", "Red Carpet");
		mapItemNames.put("171:15", "Black Carpet");
		mapItemNames.put("171:2", "Magenta Carpet");
		mapItemNames.put("171:3", "Light Blue Carpet");
		mapItemNames.put("171:4", "Yellow Carpet");
		mapItemNames.put("171:5", "Lime Carpet");
		mapItemNames.put("171:6", "Pink Carpet");
		mapItemNames.put("171:7", "Gray Carpet");
		mapItemNames.put("171:8", "Light Gray Carpet");
		mapItemNames.put("171:9", "Cyan Carpet");
		mapItemNames.put("172:0", "Hardened Clay");
		mapItemNames.put("173:0", "Block of Coal");
		mapItemNames.put("174:0", "Packed Ice");
		mapItemNames.put("175:0", "Sunflower");
		mapItemNames.put("175:1", "Lilac");
		mapItemNames.put("175:2", "Double Tallgrass");
		mapItemNames.put("175:3", "Large Fern");
		mapItemNames.put("175:4", "Rose Bush");
		mapItemNames.put("175:5", "Peony");
		mapItemNames.put("179:0", "Red Sandstone");
		mapItemNames.put("179:1", "Chiseled Red Sandstone");
		mapItemNames.put("179:2", "Smooth Red Sandstone");
		mapItemNames.put("17:0", "Oak Wood");
		mapItemNames.put("17:1", "Spruce Wood");
		mapItemNames.put("17:2", "Birch Wood");
		mapItemNames.put("17:3", "Jungle Wood");
		mapItemNames.put("17:4", "Acacia Wood");
		mapItemNames.put("17:5", "Dark Oak Wood");
		mapItemNames.put("180:0", "Red Sandstone Stairs");
		mapItemNames.put("182:0", "Red Sandstone Slab");
		mapItemNames.put("183:0", "Spruce Fence Gate");
		mapItemNames.put("184:0", "Birch Fence Gate");
		mapItemNames.put("185:0", "Jungle Fence Gate");
		mapItemNames.put("186:0", "Dark Oak Fence Gate");
		mapItemNames.put("187:0", "Acacia Fence Gate");
		mapItemNames.put("188:0", "Spruce Fence");
		mapItemNames.put("189:0", "Birch Fence");
		mapItemNames.put("18:0", "Oak Leaves");
		mapItemNames.put("18:1", "Spruce Leaves");
		mapItemNames.put("18:2", "Birch Leaves");
		mapItemNames.put("18:3", "Jungle Leaves");
		mapItemNames.put("190:0", "Jungle Fence");
		mapItemNames.put("191:0", "Dark Oak Fence");
		mapItemNames.put("192:0", "Acacia Fence");
		mapItemNames.put("19:0", "Sponge");
		mapItemNames.put("19:1", "Wet Sponge");
		mapItemNames.put("1:0", "Stone");
		mapItemNames.put("1:1", "Granite");
		mapItemNames.put("1:2", "Polished Granite");
		mapItemNames.put("1:3", "Diorite");
		mapItemNames.put("1:4", "Polished Diorite");
		mapItemNames.put("1:5", "Andesite");
		mapItemNames.put("1:6", "Polished Andesite");
		mapItemNames.put("20:0", "Glass");
		mapItemNames.put("21:0", "Lapis Lazuli Ore");
		mapItemNames.put("22:0", "Lapis Lazuli Block");
		mapItemNames.put("23:0", "Dispenser");
		mapItemNames.put("24:0", "Sandstone");
		mapItemNames.put("24:1", "Chiseled Sandstone");
		mapItemNames.put("24:2", "Smooth Sandstone");
		mapItemNames.put("256:0", "Iron Shovel");
		mapItemNames.put("257:0", "Iron Pickaxe");
		mapItemNames.put("258:0", "Iron Axe");
		mapItemNames.put("259:0", "Flint and Steel");
		mapItemNames.put("25:0", "Note Block");
		mapItemNames.put("260:0", "Apple");
		mapItemNames.put("261:0", "Bow");
		mapItemNames.put("262:0", "Arrow");
		mapItemNames.put("263:0", "Coal");
		mapItemNames.put("263:1", "Charcoal");
		mapItemNames.put("264:0", "Diamond");
		mapItemNames.put("265:0", "Iron Ingot");
		mapItemNames.put("266:0", "Gold Ingot");
		mapItemNames.put("267:0", "Iron Sword");
		mapItemNames.put("268:0", "Wooden Sword");
		mapItemNames.put("269:0", "Wooden Shovel");
		mapItemNames.put("270:0", "Wooden Pickaxe");
		mapItemNames.put("271:0", "Wooden Axe");
		mapItemNames.put("272:0", "Stone Sword");
		mapItemNames.put("273:0", "Stone Shovel");
		mapItemNames.put("274:0", "Stone Pickaxe");
		mapItemNames.put("275:0", "Stone Axe");
		mapItemNames.put("276:0", "Diamond Sword");
		mapItemNames.put("277:0", "Diamond Shovel");
		mapItemNames.put("278:0", "Diamond Pickaxe");
		mapItemNames.put("279:0", "Diamond Axe");
		mapItemNames.put("27:0", "Powered Rail");
		mapItemNames.put("280:0", "Stick");
		mapItemNames.put("281:0", "Bowl");
		mapItemNames.put("282:0", "Mushroom Stew");
		mapItemNames.put("283:0", "Golden Sword");
		mapItemNames.put("284:0", "Golden Shovel");
		mapItemNames.put("285:0", "Golden Pickaxe");
		mapItemNames.put("286:0", "Golden Axe");
		mapItemNames.put("287:0", "String");
		mapItemNames.put("288:0", "Feather");
		mapItemNames.put("289:0", "Gunpowder");
		mapItemNames.put("28:0", "Detector Rail");
		mapItemNames.put("290:0", "Wooden Hoe");
		mapItemNames.put("291:0", "Stone Hoe");
		mapItemNames.put("292:0", "Iron Hoe");
		mapItemNames.put("293:0", "Diamond Hoe");
		mapItemNames.put("294:0", "Golden Hoe");
		mapItemNames.put("295:0", "Seeds");
		mapItemNames.put("296:0", "Wheat");
		mapItemNames.put("297:0", "Bread");
		mapItemNames.put("298:0", "Leather Cap");
		mapItemNames.put("299:0", "Leather Tunic");
		mapItemNames.put("29:0", "Sticky Piston");
		mapItemNames.put("2:0", "Grass Block");
		mapItemNames.put("300:0", "Leather Pants");
		mapItemNames.put("301:0", "Leather Boots");
		mapItemNames.put("302:0", "Chain Helmet");
		mapItemNames.put("303:0", "Chain Chestplate");
		mapItemNames.put("304:0", "Chain Leggings");
		mapItemNames.put("305:0", "Chain Boots");
		mapItemNames.put("306:0", "Iron Helmet");
		mapItemNames.put("307:0", "Iron Chestplate");
		mapItemNames.put("308:0", "Iron Leggings");
		mapItemNames.put("309:0", "Iron Boots");
		mapItemNames.put("30:0", "Cobweb");
		mapItemNames.put("310:0", "Diamond Helmet");
		mapItemNames.put("311:0", "Diamond Chestplate");
		mapItemNames.put("312:0", "Diamond Leggings");
		mapItemNames.put("313:0", "Diamond Boots");
		mapItemNames.put("314:0", "Golden Helmet");
		mapItemNames.put("315:0", "Golden Chestplate");
		mapItemNames.put("316:0", "Golden Leggings");
		mapItemNames.put("317:0", "Golden Boots");
		mapItemNames.put("318:0", "Flint");
		mapItemNames.put("319:0", "Raw Porkchop");
		mapItemNames.put("31:0", "Shrub");
		mapItemNames.put("31:1", "Grass");
		mapItemNames.put("31:2", "Fern");
		mapItemNames.put("320:0", "Cooked Porkchop");
		mapItemNames.put("321:0", "Painting");
		mapItemNames.put("322:0", "Golden Apple");
		mapItemNames.put("323:0", "Sign");
		mapItemNames.put("324:0", "Oak Door");
		mapItemNames.put("325:0", "Bucket");
		mapItemNames.put("326:0", "Water Bucket");
		mapItemNames.put("327:0", "Lava Bucket");
		mapItemNames.put("328:0", "Minecart");
		mapItemNames.put("329:0", "Saddle");
		mapItemNames.put("32:0", "Dead Bush");
		mapItemNames.put("330:0", "Iron Door");
		mapItemNames.put("331:0", "Redstone");
		mapItemNames.put("332:0", "Snowball");
		mapItemNames.put("333:0", "Boat");
		mapItemNames.put("334:0", "Leather");
		mapItemNames.put("335:0", "Milk");
		mapItemNames.put("336:0", "Brick");
		mapItemNames.put("338:0", "Sugar Canes");
		mapItemNames.put("339:0", "Paper");
		mapItemNames.put("33:0", "Piston");
		mapItemNames.put("340:0", "Book");
		mapItemNames.put("341:0", "Slimeball");
		mapItemNames.put("342:0", "Minecart with Chest");
		mapItemNames.put("343:0", "Minecart with Furnace");
		mapItemNames.put("344:0", "Egg");
		mapItemNames.put("345:0", "Compass");
		mapItemNames.put("346:0", "Fishing Rod");
		mapItemNames.put("347:0", "Clock");
		mapItemNames.put("348:0", "Glowstone Dust");
		mapItemNames.put("349:0", "Raw Fish");
		mapItemNames.put("349:1", "Raw Salmon");
		mapItemNames.put("349:2", "Clownfish");
		mapItemNames.put("349:3", "Pufferfish");
		mapItemNames.put("350:0", "Cooked Fish");
		mapItemNames.put("350:1", "Cooked Salmon");
		mapItemNames.put("351:0", "Ink Sac");
		mapItemNames.put("351:1", "Rose Red");
		mapItemNames.put("351:10", "Lime Dye");
		mapItemNames.put("351:11", "Dandelion Yellow");
		mapItemNames.put("351:12", "Light Blue Dye");
		mapItemNames.put("351:13", "Magenta Dye");
		mapItemNames.put("351:14", "Orange Dye");
		mapItemNames.put("351:15", "Bone Meal");
		mapItemNames.put("351:2", "Cactus Green");
		mapItemNames.put("351:3", "Cocoa Beans");
		mapItemNames.put("351:4", "Lapis Lazuli");
		mapItemNames.put("351:5", "Purple Dye");
		mapItemNames.put("351:6", "Cyan Dye");
		mapItemNames.put("351:7", "Light Gray Dye");
		mapItemNames.put("351:8", "Gray Dye");
		mapItemNames.put("351:9", "Pink Dye");
		mapItemNames.put("352:0", "Bone");
		mapItemNames.put("353:0", "Sugar");
		mapItemNames.put("354:0", "Cake");
		mapItemNames.put("355:0", "Bed");
		mapItemNames.put("356:0", "Redstone Repeater");
		mapItemNames.put("357:0", "Cookie");
		mapItemNames.put("358:0", "Map");
		mapItemNames.put("359:0", "Shears");
		mapItemNames.put("35:0", "Wool");
		mapItemNames.put("35:1", "Orange Wool");
		mapItemNames.put("35:10", "Purple Wool");
		mapItemNames.put("35:11", "Blue Wool");
		mapItemNames.put("35:12", "Brown Wool");
		mapItemNames.put("35:13", "Green Wool");
		mapItemNames.put("35:14", "Red Wool");
		mapItemNames.put("35:15", "Black Wool");
		mapItemNames.put("35:2", "Magenta Wool");
		mapItemNames.put("35:3", "Light Blue Wool");
		mapItemNames.put("35:4", "Yellow Wool");
		mapItemNames.put("35:5", "Lime Wool");
		mapItemNames.put("35:6", "Pink Wool");
		mapItemNames.put("35:7", "Gray Wool");
		mapItemNames.put("35:8", "Light Gray Wool");
		mapItemNames.put("35:9", "Cyan Wool");
		mapItemNames.put("361:0", "Pumpkin Seeds");
		mapItemNames.put("362:0", "Melon Seeds");
		mapItemNames.put("363:0", "Raw Beef");
		mapItemNames.put("364:0", "Steak");
		mapItemNames.put("365:0", "Raw Chicken");
		mapItemNames.put("366:0", "Cooked Chicken");
		mapItemNames.put("367:0", "Rotten Flesh");
		mapItemNames.put("368:0", "Ender Pearl");
		mapItemNames.put("369:0", "Blaze Rod");
		mapItemNames.put("370:0", "Ghast Tear");
		mapItemNames.put("371:0", "Gold Nugget");
		mapItemNames.put("372:0", "Nether Wart");
		mapItemNames.put("373:0", "Water Bottle");
		mapItemNames.put("373:1", "Potion of Regeneration");
		mapItemNames.put("373:10", "Potion of Slowness");
		mapItemNames.put("373:11", "Potion of Leaping");
		mapItemNames.put("373:12", "Potion of Harming");
		mapItemNames.put("373:13", "Potion of Water Breathing");
		mapItemNames.put("373:14", "Potion of Invisibility");
		mapItemNames.put("373:15", "Thin Potion");
		mapItemNames.put("373:16", "Awkward Potion");
		mapItemNames.put("373:2", "Potion of Swiftness");
		mapItemNames.put("373:3", "Potion of Fire Resistance");
		mapItemNames.put("373:4", "Potion of Poison");
		mapItemNames.put("373:5", "Potion of Healing");
		mapItemNames.put("373:6", "Potion of Night Vision");
		mapItemNames.put("373:7", "Clear Potion");
		mapItemNames.put("373:8", "Potion of Weakness");
		mapItemNames.put("373:9", "Potion of Strength");
		mapItemNames.put("374:0", "Glass Bottle");
		mapItemNames.put("375:0", "Spider Eye");
		mapItemNames.put("376:0", "Fermented Spider Eye");
		mapItemNames.put("377:0", "Blaze Powder");
		mapItemNames.put("378:0", "Magma Cream");
		mapItemNames.put("379:0", "Brewing Stand");
		mapItemNames.put("37:0", "Dandelion");
		mapItemNames.put("380:0", "Cauldron");
		mapItemNames.put("381:0", "Eye of Ender");
		mapItemNames.put("382:0", "Glistering Melon");
		mapItemNames.put("383:0", "Spawn");
		mapItemNames.put("383:1", "Spawn Item");
		mapItemNames.put("383:2", "Spawn Experience Orb");
		mapItemNames.put("384:0", "Bottle o' Enchanting");
		mapItemNames.put("385:0", "Fire Charge");
		mapItemNames.put("386:0", "Book and Quill");
		mapItemNames.put("387:0", "Written Book");
		mapItemNames.put("388:0", "Emerald");
		mapItemNames.put("389:0", "Item Frame");
		mapItemNames.put("38:0", "Poppy");
		mapItemNames.put("38:1", "Blue Orchid");
		mapItemNames.put("38:2", "Allium");
		mapItemNames.put("38:3", "Azure Bluet");
		mapItemNames.put("38:4", "Red Tulip");
		mapItemNames.put("38:5", "Orange Tulip");
		mapItemNames.put("38:6", "White Tulip");
		mapItemNames.put("38:7", "Pink Tulip");
		mapItemNames.put("38:8", "Oxeye Daisy");
		mapItemNames.put("390:0", "Flower Pot");
		mapItemNames.put("391:0", "Carrot");
		mapItemNames.put("392:0", "Potato");
		mapItemNames.put("393:0", "Baked Potato");
		mapItemNames.put("394:0", "Poisonous Potato");
		mapItemNames.put("395:0", "Empty Map");
		mapItemNames.put("396:0", "Golden Carrot");
		mapItemNames.put("397:0", "Skeleton Skull");
		mapItemNames.put("397:1", "Wither Skeleton Skull");
		mapItemNames.put("397:2", "Zombie Head");
		mapItemNames.put("397:3", "Head");
		mapItemNames.put("397:4", "Creeper Head");
		mapItemNames.put("398:0", "Carrot on a Stick");
		mapItemNames.put("399:0", "Nether Star");
		mapItemNames.put("39:0", "Mushroom");
		mapItemNames.put("3:0", "Dirt");
		mapItemNames.put("3:1", "Coarse Dirt");
		mapItemNames.put("3:2", "Podzol");
		mapItemNames.put("400:0", "Pumpkin Pie");
		mapItemNames.put("401:0", "Firework Rocket");
		mapItemNames.put("402:0", "Firework Star");
		mapItemNames.put("403:0", "Enchanted Book");
		mapItemNames.put("404:0", "Redstone Comparator");
		mapItemNames.put("406:0", "Nether Quartz");
		mapItemNames.put("407:0", "Minecart with TNT");
		mapItemNames.put("408:0", "Minecart with Hopper");
		mapItemNames.put("409:0", "Prismarine Shard");
		mapItemNames.put("410:0", "Prismarine Crystals");
		mapItemNames.put("411:0", "Raw Rabbit");
		mapItemNames.put("412:0", "Cooked Rabbit");
		mapItemNames.put("413:0", "Rabbit Stew");
		mapItemNames.put("414:0", "Rabbit's Foot");
		mapItemNames.put("415:0", "Rabbit Hide");
		mapItemNames.put("416:0", "Armor Stand");
		mapItemNames.put("417:0", "Iron Horse Armor");
		mapItemNames.put("418:0", "Gold Horse Armor");
		mapItemNames.put("419:0", "Diamond Horse Armor");
		mapItemNames.put("41:0", "Block of Gold");
		mapItemNames.put("420:0", "Lead");
		mapItemNames.put("421:0", "Name Tag");
		mapItemNames.put("422:0", "Minecart with Command Block");
		mapItemNames.put("423:0", "Raw Mutton");
		mapItemNames.put("424:0", "Cooked Mutton");
		mapItemNames.put("425:0", "Black Banner");
		mapItemNames.put("425:1", "Red Banner");
		mapItemNames.put("425:10", "Lime Banner");
		mapItemNames.put("425:11", "Yellow Banner");
		mapItemNames.put("425:12", "Light Blue Banner");
		mapItemNames.put("425:13", "Magenta Banner");
		mapItemNames.put("425:14", "Orange Banner");
		mapItemNames.put("425:15", "White Banner");
		mapItemNames.put("425:2", "Green Banner");
		mapItemNames.put("425:3", "Brown Banner");
		mapItemNames.put("425:4", "Blue Banner");
		mapItemNames.put("425:5", "Purple Banner");
		mapItemNames.put("425:6", "Cyan Banner");
		mapItemNames.put("425:7", "Light Gray Banner");
		mapItemNames.put("425:8", "Gray Banner");
		mapItemNames.put("425:9", "Pink Banner");
		mapItemNames.put("427:0", "Spruce Door");
		mapItemNames.put("428:0", "Birch Door");
		mapItemNames.put("429:0", "Jungle Door");
		mapItemNames.put("42:0", "Block of Iron");
		mapItemNames.put("430:0", "Acacia Door");
		mapItemNames.put("431:0", "Dark Oak Door");
		mapItemNames.put("44:0", "Stone Slab");
		mapItemNames.put("44:1", "Sandstone Slab");
		mapItemNames.put("44:2", "Wooden Slab");
		mapItemNames.put("44:3", "Cobblestone Slab");
		mapItemNames.put("44:4", "Bricks Slab");
		mapItemNames.put("44:5", "Stone Bricks Slab");
		mapItemNames.put("44:6", "Nether Brick Slab");
		mapItemNames.put("44:7", "Quartz Slab");
		mapItemNames.put("45:0", "Bricks");
		mapItemNames.put("46:0", "TNT");
		mapItemNames.put("47:0", "Bookshelf");
		mapItemNames.put("48:0", "Moss Stone");
		mapItemNames.put("49:0", "Obsidian");
		mapItemNames.put("4:0", "Cobblestone");
		mapItemNames.put("50:0", "Torch");
		mapItemNames.put("52:0", "Monster Spawner");
		mapItemNames.put("53:0", "Oak Wood Stairs");
		mapItemNames.put("54:0", "Chest");
		mapItemNames.put("56:0", "Diamond Ore");
		mapItemNames.put("57:0", "Block of Diamond");
		mapItemNames.put("58:0", "Crafting Table");
		mapItemNames.put("5:0", "Oak Wood Planks");
		mapItemNames.put("5:1", "Spruce Wood Planks");
		mapItemNames.put("5:2", "Birch Wood Planks");
		mapItemNames.put("5:3", "Jungle Wood Planks");
		mapItemNames.put("5:4", "Acacia Wood Planks");
		mapItemNames.put("5:5", "Dark Oak Wood Planks");
		mapItemNames.put("60:0", "Farmland");
		mapItemNames.put("61:0", "Furnace");
		mapItemNames.put("65:0", "Ladder");
		mapItemNames.put("66:0", "Rail");
		mapItemNames.put("67:0", "Cobblestone Stairs");
		mapItemNames.put("69:0", "Lever");
		mapItemNames.put("6:0", "Oak Sapling");
		mapItemNames.put("6:1", "Spruce Sapling");
		mapItemNames.put("6:2", "Birch Sapling");
		mapItemNames.put("6:3", "Jungle Sapling");
		mapItemNames.put("6:4", "Acacia Sapling");
		mapItemNames.put("6:5", "Dark Oak Sapling");
		mapItemNames.put("70:0", "Stone Pressure Plate");
		mapItemNames.put("72:0", "Wooden Pressure Plate");
		mapItemNames.put("73:0", "Redstone Ore");
		mapItemNames.put("76:0", "Redstone Torch");
		mapItemNames.put("77:0", "Button");
		mapItemNames.put("78:0", "Snow");
		mapItemNames.put("79:0", "Ice");
		mapItemNames.put("7:0", "Bedrock");
		mapItemNames.put("81:0", "Cactus");
		mapItemNames.put("82:0", "Clay");
		mapItemNames.put("84:0", "Jukebox");
		mapItemNames.put("85:0", "Oak Fence");
		mapItemNames.put("86:0", "Pumpkin");
		mapItemNames.put("87:0", "Netherrack");
		mapItemNames.put("88:0", "Soul Sand");
		mapItemNames.put("89:0", "Glowstone");
		mapItemNames.put("91:0", "Jack o'Lantern");
		mapItemNames.put("95:0", "White Stained Glass");
		mapItemNames.put("95:1", "Orange Stained Glass");
		mapItemNames.put("95:10", "Purple Stained Glass");
		mapItemNames.put("95:11", "Blue Stained Glass");
		mapItemNames.put("95:12", "Brown Stained Glass");
		mapItemNames.put("95:13", "Green Stained Glass");
		mapItemNames.put("95:14", "Red Stained Glass");
		mapItemNames.put("95:15", "Black Stained Glass");
		mapItemNames.put("95:2", "Magenta Stained Glass");
		mapItemNames.put("95:3", "Light Blue Stained Glass");
		mapItemNames.put("95:4", "Yellow Stained Glass");
		mapItemNames.put("95:5", "Lime Stained Glass");
		mapItemNames.put("95:6", "Pink Stained Glass");
		mapItemNames.put("95:7", "Gray Stained Glass");
		mapItemNames.put("95:8", "Light Gray Stained Glass");
		mapItemNames.put("95:9", "Cyan Stained Glass");
		mapItemNames.put("96:0", "Wooden Trapdoor");
		mapItemNames.put("97:0", "Stone Monster Egg");
		mapItemNames.put("97:1", "Cobblestone Monster Egg");
		mapItemNames.put("97:2", "Stone Brick Monster Egg");
		mapItemNames.put("97:3", "Mossy Stone Brick Monster Egg");
		mapItemNames.put("97:4", "Cracked Stone Brick Monster Egg");
		mapItemNames.put("97:5", "Chiseled Stone Brick Monster Egg");
		mapItemNames.put("98:0", "Stone Bricks");
		mapItemNames.put("98:1", "Mossy Stone Bricks");
		mapItemNames.put("98:2", "Cracked Stone Bricks");
		mapItemNames.put("98:3", "Chiseled Stone Bricks");

		// Manual Fixes
		// -----------------------------
	      //initFunc(178, "daylight_detector_inverted", new BlockDaylightDetector(true));
		mapItemNames.put("162:0", "Acacia Wood");
		mapItemNames.put("162:1", "Dark Oak Wood");
		mapNumSubtypes.put(162, 2);
		
		mapItemNames.put("178:0", "Daylight Detector (Inverted)"); // daylight_detector_inverted
		mapNumSubtypes.put(178, 1);
		
		mapItemNames.put("93:0", "Repeater (Unpowered)");
		mapItemNames.put("94:0", "Repeater (Powered)");
		mapNumSubtypes.put(93, 1);
		mapNumSubtypes.put(94, 1);

		
		mapItemNames.put("149:0", "Comparator (Unpowered)");
		mapItemNames.put("150:0", "Comparator (Powered)");
		mapNumSubtypes.put(149, 1);
		mapNumSubtypes.put(150, 1);

		mapItemNames.put("100:0", "Red Mushroom Block");
		mapNumSubtypes.put(100, 1);

		mapItemNames.put("80:0", "Snow");
		mapNumSubtypes.put(80, 1);

		mapItemNames.put("43:0", "Double Stone Slab");
		mapNumSubtypes.put(43, 1);

		mapItemNames.put("117:0", "Brewing Stand");
		mapNumSubtypes.put(117, 1);

		mapItemNames.put("125:0", "Double Wooden Slab");
		mapNumSubtypes.put(125, 1);

		mapItemNames.put("62:0", "Furnace (Lit)");
		mapNumSubtypes.put(62, 1);

		mapItemNames.put("132:0", "Tripwire");
		mapNumSubtypes.put(132, 1);

		mapItemNames.put("140:0", "Flower Pot");
		mapNumSubtypes.put(140, 1);

		mapItemNames.put("181:0", "Double Stone Slab 2");
		mapNumSubtypes.put(181, 1);

		mapItemNames.put("119:0", "End Portal");
		mapNumSubtypes.put(119, 1);

		mapItemNames.put("99:0", "Brown Mushroom Block");
		mapNumSubtypes.put(99, 1);

		mapItemNames.put("118:0", "Cauldron");
		mapNumSubtypes.put(118, 1);

		mapItemNames.put("74:0", "Redstone Ore (Lit)");
		mapNumSubtypes.put(74, 1);

		mapItemNames.put("144:0", "Skull");
		mapNumSubtypes.put(144, 1);


		mapItemNames.put("63:0", "Sign (Standing)");
		mapNumSubtypes.put(63, 1);

		mapItemNames.put("176:0", "Banner (Standing)");
		mapNumSubtypes.put(176, 1);
		
		// -----------------------------
		
		mapNumSubtypes.put(1, 7);
		mapNumSubtypes.put(2, 1);
		mapNumSubtypes.put(3, 3);
		mapNumSubtypes.put(4, 1);
		mapNumSubtypes.put(5, 6);
		mapNumSubtypes.put(6, 6);
		mapNumSubtypes.put(7, 1);
		mapNumSubtypes.put(12, 2);
		mapNumSubtypes.put(13, 1);
		mapNumSubtypes.put(14, 1);
		mapNumSubtypes.put(15, 1);
		mapNumSubtypes.put(16, 1);
		mapNumSubtypes.put(17, 6);
		mapNumSubtypes.put(18, 4);
		mapNumSubtypes.put(19, 2);
		mapNumSubtypes.put(20, 1);
		mapNumSubtypes.put(21, 1);
		mapNumSubtypes.put(22, 1);
		mapNumSubtypes.put(23, 1);
		mapNumSubtypes.put(24, 3);
		mapNumSubtypes.put(25, 1);
		mapNumSubtypes.put(27, 1);
		mapNumSubtypes.put(28, 1);
		mapNumSubtypes.put(29, 1);
		mapNumSubtypes.put(30, 1);
		mapNumSubtypes.put(31, 3);
		mapNumSubtypes.put(32, 1);
		mapNumSubtypes.put(33, 1);
		mapNumSubtypes.put(35, 16);
		mapNumSubtypes.put(37, 1);
		mapNumSubtypes.put(38, 9);
		mapNumSubtypes.put(39, 1);
		mapNumSubtypes.put(41, 1);
		mapNumSubtypes.put(42, 1);
		mapNumSubtypes.put(44, 8);
		mapNumSubtypes.put(45, 1);
		mapNumSubtypes.put(46, 1);
		mapNumSubtypes.put(47, 1);
		mapNumSubtypes.put(48, 1);
		mapNumSubtypes.put(49, 1);
		mapNumSubtypes.put(50, 1);
		mapNumSubtypes.put(52, 1);
		mapNumSubtypes.put(53, 1);
		mapNumSubtypes.put(54, 1);
		mapNumSubtypes.put(56, 1);
		mapNumSubtypes.put(57, 1);
		mapNumSubtypes.put(58, 1);
		mapNumSubtypes.put(60, 1);
		mapNumSubtypes.put(61, 1);
		mapNumSubtypes.put(65, 1);
		mapNumSubtypes.put(66, 1);
		mapNumSubtypes.put(67, 1);
		mapNumSubtypes.put(69, 1);
		mapNumSubtypes.put(70, 1);
		mapNumSubtypes.put(72, 1);
		mapNumSubtypes.put(73, 1);
		mapNumSubtypes.put(76, 1);
		mapNumSubtypes.put(77, 1);
		mapNumSubtypes.put(78, 1);
		mapNumSubtypes.put(79, 1);
		mapNumSubtypes.put(81, 1);
		mapNumSubtypes.put(82, 1);
		mapNumSubtypes.put(84, 1);
		mapNumSubtypes.put(85, 1);
		mapNumSubtypes.put(86, 1);
		mapNumSubtypes.put(87, 1);
		mapNumSubtypes.put(88, 1);
		mapNumSubtypes.put(89, 1);
		mapNumSubtypes.put(91, 1);
		mapNumSubtypes.put(95, 16);
		mapNumSubtypes.put(96, 1);
		mapNumSubtypes.put(97, 6);
		mapNumSubtypes.put(98, 4);
		mapNumSubtypes.put(101, 1);
		mapNumSubtypes.put(102, 1);
		mapNumSubtypes.put(103, 1);
		mapNumSubtypes.put(106, 1);
		mapNumSubtypes.put(107, 1);
		mapNumSubtypes.put(108, 1);
		mapNumSubtypes.put(109, 1);
		mapNumSubtypes.put(110, 1);
		mapNumSubtypes.put(111, 1);
		mapNumSubtypes.put(112, 1);
		mapNumSubtypes.put(113, 1);
		mapNumSubtypes.put(114, 1);
		mapNumSubtypes.put(116, 1);
		mapNumSubtypes.put(120, 1);
		mapNumSubtypes.put(121, 1);
		mapNumSubtypes.put(122, 1);
		mapNumSubtypes.put(123, 1);
		mapNumSubtypes.put(126, 6);
		mapNumSubtypes.put(128, 1);
		mapNumSubtypes.put(129, 1);
		mapNumSubtypes.put(130, 1);
		mapNumSubtypes.put(131, 1);
		mapNumSubtypes.put(133, 1);
		mapNumSubtypes.put(134, 1);
		mapNumSubtypes.put(135, 1);
		mapNumSubtypes.put(136, 1);
		mapNumSubtypes.put(137, 1);
		mapNumSubtypes.put(138, 1);
		mapNumSubtypes.put(139, 2);
		mapNumSubtypes.put(145, 3);
		mapNumSubtypes.put(146, 1);
		mapNumSubtypes.put(147, 1);
		mapNumSubtypes.put(148, 1);
		mapNumSubtypes.put(151, 1);
		mapNumSubtypes.put(152, 1);
		mapNumSubtypes.put(153, 1);
		mapNumSubtypes.put(154, 1);
		mapNumSubtypes.put(155, 3);
		mapNumSubtypes.put(156, 1);
		mapNumSubtypes.put(157, 1);
		mapNumSubtypes.put(158, 1);
		mapNumSubtypes.put(159, 16);
		mapNumSubtypes.put(160, 16);
		mapNumSubtypes.put(161, 2);
		mapNumSubtypes.put(162, 2);		
		mapNumSubtypes.put(163, 1);
		mapNumSubtypes.put(164, 1);
		mapNumSubtypes.put(165, 1);
		mapNumSubtypes.put(166, 1);
		mapNumSubtypes.put(167, 1);
		mapNumSubtypes.put(168, 3);
		mapNumSubtypes.put(169, 1);
		mapNumSubtypes.put(170, 1);
		mapNumSubtypes.put(171, 16);
		mapNumSubtypes.put(172, 1);
		mapNumSubtypes.put(173, 1);
		mapNumSubtypes.put(174, 1);
		mapNumSubtypes.put(175, 6);
		mapNumSubtypes.put(179, 3);
		mapNumSubtypes.put(180, 1);
		mapNumSubtypes.put(182, 1);
		mapNumSubtypes.put(183, 1);
		mapNumSubtypes.put(184, 1);
		mapNumSubtypes.put(185, 1);
		mapNumSubtypes.put(186, 1);
		mapNumSubtypes.put(187, 1);
		mapNumSubtypes.put(188, 1);
		mapNumSubtypes.put(189, 1);
		mapNumSubtypes.put(190, 1);
		mapNumSubtypes.put(191, 1);
		mapNumSubtypes.put(192, 1);
		mapNumSubtypes.put(256, 1);
		mapNumSubtypes.put(257, 1);
		mapNumSubtypes.put(258, 1);
		mapNumSubtypes.put(259, 1);
		mapNumSubtypes.put(260, 1);
		mapNumSubtypes.put(261, 1);
		mapNumSubtypes.put(262, 1);
		mapNumSubtypes.put(263, 2);
		mapNumSubtypes.put(264, 1);
		mapNumSubtypes.put(265, 1);
		mapNumSubtypes.put(266, 1);
		mapNumSubtypes.put(267, 1);
		mapNumSubtypes.put(268, 1);
		mapNumSubtypes.put(269, 1);
		mapNumSubtypes.put(270, 1);
		mapNumSubtypes.put(271, 1);
		mapNumSubtypes.put(272, 1);
		mapNumSubtypes.put(273, 1);
		mapNumSubtypes.put(274, 1);
		mapNumSubtypes.put(275, 1);
		mapNumSubtypes.put(276, 1);
		mapNumSubtypes.put(277, 1);
		mapNumSubtypes.put(278, 1);
		mapNumSubtypes.put(279, 1);
		mapNumSubtypes.put(280, 1);
		mapNumSubtypes.put(281, 1);
		mapNumSubtypes.put(282, 1);
		mapNumSubtypes.put(283, 1);
		mapNumSubtypes.put(284, 1);
		mapNumSubtypes.put(285, 1);
		mapNumSubtypes.put(286, 1);
		mapNumSubtypes.put(287, 1);
		mapNumSubtypes.put(288, 1);
		mapNumSubtypes.put(289, 1);
		mapNumSubtypes.put(290, 1);
		mapNumSubtypes.put(291, 1);
		mapNumSubtypes.put(292, 1);
		mapNumSubtypes.put(293, 1);
		mapNumSubtypes.put(294, 1);
		mapNumSubtypes.put(295, 1);
		mapNumSubtypes.put(296, 1);
		mapNumSubtypes.put(297, 1);
		mapNumSubtypes.put(298, 1);
		mapNumSubtypes.put(299, 1);
		mapNumSubtypes.put(300, 1);
		mapNumSubtypes.put(301, 1);
		mapNumSubtypes.put(302, 1);
		mapNumSubtypes.put(303, 1);
		mapNumSubtypes.put(304, 1);
		mapNumSubtypes.put(305, 1);
		mapNumSubtypes.put(306, 1);
		mapNumSubtypes.put(307, 1);
		mapNumSubtypes.put(308, 1);
		mapNumSubtypes.put(309, 1);
		mapNumSubtypes.put(310, 1);
		mapNumSubtypes.put(311, 1);
		mapNumSubtypes.put(312, 1);
		mapNumSubtypes.put(313, 1);
		mapNumSubtypes.put(314, 1);
		mapNumSubtypes.put(315, 1);
		mapNumSubtypes.put(316, 1);
		mapNumSubtypes.put(317, 1);
		mapNumSubtypes.put(318, 1);
		mapNumSubtypes.put(319, 1);
		mapNumSubtypes.put(320, 1);
		mapNumSubtypes.put(321, 1);
		mapNumSubtypes.put(322, 1);
		mapNumSubtypes.put(323, 1);
		mapNumSubtypes.put(324, 1);
		mapNumSubtypes.put(325, 1);
		mapNumSubtypes.put(326, 1);
		mapNumSubtypes.put(327, 1);
		mapNumSubtypes.put(328, 1);
		mapNumSubtypes.put(329, 1);
		mapNumSubtypes.put(330, 1);
		mapNumSubtypes.put(331, 1);
		mapNumSubtypes.put(332, 1);
		mapNumSubtypes.put(333, 1);
		mapNumSubtypes.put(334, 1);
		mapNumSubtypes.put(335, 1);
		mapNumSubtypes.put(336, 1);
		mapNumSubtypes.put(338, 1);
		mapNumSubtypes.put(339, 1);
		mapNumSubtypes.put(340, 1);
		mapNumSubtypes.put(341, 1);
		mapNumSubtypes.put(342, 1);
		mapNumSubtypes.put(343, 1);
		mapNumSubtypes.put(344, 1);
		mapNumSubtypes.put(345, 1);
		mapNumSubtypes.put(346, 1);
		mapNumSubtypes.put(347, 1);
		mapNumSubtypes.put(348, 1);
		mapNumSubtypes.put(349, 4);
		mapNumSubtypes.put(350, 2);
		mapNumSubtypes.put(351, 16);
		mapNumSubtypes.put(352, 1);
		mapNumSubtypes.put(353, 1);
		mapNumSubtypes.put(354, 1);
		mapNumSubtypes.put(355, 1);
		mapNumSubtypes.put(356, 1);
		mapNumSubtypes.put(357, 1);
		mapNumSubtypes.put(358, 1);
		mapNumSubtypes.put(359, 1);
		mapNumSubtypes.put(361, 1);
		mapNumSubtypes.put(362, 1);
		mapNumSubtypes.put(363, 1);
		mapNumSubtypes.put(364, 1);
		mapNumSubtypes.put(365, 1);
		mapNumSubtypes.put(366, 1);
		mapNumSubtypes.put(367, 1);
		mapNumSubtypes.put(368, 1);
		mapNumSubtypes.put(369, 1);
		mapNumSubtypes.put(370, 1);
		mapNumSubtypes.put(371, 1);
		mapNumSubtypes.put(372, 1);
		mapNumSubtypes.put(373, 17);
		mapNumSubtypes.put(374, 1);
		mapNumSubtypes.put(375, 1);
		mapNumSubtypes.put(376, 1);
		mapNumSubtypes.put(377, 1);
		mapNumSubtypes.put(378, 1);
		mapNumSubtypes.put(379, 1);
		mapNumSubtypes.put(380, 1);
		mapNumSubtypes.put(381, 1);
		mapNumSubtypes.put(382, 1);
		mapNumSubtypes.put(383, 3);
		mapNumSubtypes.put(384, 1);
		mapNumSubtypes.put(385, 1);
		mapNumSubtypes.put(386, 1);
		mapNumSubtypes.put(387, 1);
		mapNumSubtypes.put(388, 1);
		mapNumSubtypes.put(389, 1);
		mapNumSubtypes.put(390, 1);
		mapNumSubtypes.put(391, 1);
		mapNumSubtypes.put(392, 1);
		mapNumSubtypes.put(393, 1);
		mapNumSubtypes.put(394, 1);
		mapNumSubtypes.put(395, 1);
		mapNumSubtypes.put(396, 1);
		mapNumSubtypes.put(397, 5);
		mapNumSubtypes.put(398, 1);
		mapNumSubtypes.put(399, 1);
		mapNumSubtypes.put(400, 1);
		mapNumSubtypes.put(401, 1);
		mapNumSubtypes.put(402, 1);
		mapNumSubtypes.put(403, 1);
		mapNumSubtypes.put(404, 1);
		mapNumSubtypes.put(406, 1);
		mapNumSubtypes.put(407, 1);
		mapNumSubtypes.put(408, 1);
		mapNumSubtypes.put(409, 1);
		mapNumSubtypes.put(410, 1);
		mapNumSubtypes.put(411, 1);
		mapNumSubtypes.put(412, 1);
		mapNumSubtypes.put(413, 1);
		mapNumSubtypes.put(414, 1);
		mapNumSubtypes.put(415, 1);
		mapNumSubtypes.put(416, 1);
		mapNumSubtypes.put(417, 1);
		mapNumSubtypes.put(418, 1);
		mapNumSubtypes.put(419, 1);
		mapNumSubtypes.put(420, 1);
		mapNumSubtypes.put(421, 1);
		mapNumSubtypes.put(422, 1);
		mapNumSubtypes.put(423, 1);
		mapNumSubtypes.put(424, 1);
		mapNumSubtypes.put(425, 16);
		mapNumSubtypes.put(427, 1);
		mapNumSubtypes.put(428, 1);
		mapNumSubtypes.put(429, 1);
		mapNumSubtypes.put(430, 1);
		mapNumSubtypes.put(431, 1);
		
		
		
	}

}
